### ISSUE TITLE
Bug: Category ordering in Multiple Selection Mode 

### ISSUE THREAD

**Issue by aniqueta** [eneiluj/cospend-nc#85] opened 2021-09-26 21:50 UTC
Thanks for this useful utility. When in Multiple Selection mode, the category ordering in the drop down menu does not follow either alphabetical ordering or manual ordering as selected in the project settings.

**Comment by eneiluj** [comment] 2021-09-27 00:17
Hi. I can't reproduce the issue. Categories are ordered correctly in the multiple selection selector. Which version of Cospend are you using?

**Comment by aniqueta** [comment] 2021-09-27 01:00
Hm… 1.3.7. Tested in both Safari and Firefox and using a new project. Also toggled Alphabetical and Manual, and then refreshed browser. 
<img width="429" alt="Screen Shot 2021-09-26 at 5 58 32 PM" src="https://user-images.githubusercontent.com/65845439/134830983-9aa820d9-2bf7-4618-a2b2-956a14971fdb.png">
<img width="191" alt="Screen Shot 2021-09-26 at 5 58 15 PM" src="https://user-images.githubusercontent.com/65845439/134830986-a4cf6cb8-b793-4706-a050-6afdd31a2b57.png">

**Comment by aniqueta** [comment] 2021-09-27 01:06
I should also note I'm on NC 21.0.4, and Cospend 1.3.7 appears to be the more recent version that's available and compatible with this version of NC. As an old user of Cospend, for me, this issue has existed from at least the introduction of the alphabetical ordering option several versions ago. I just didn't have a moment to file an issue until now.

**Comment by eneiluj** [comment] 2021-09-27 08:54
It is fixed in more recent versions of Cospend. Sorry, NC <= 21 will not receive those updates.

Btw, the beauty of Vue.JS (framework used in Cospend) is that everything is dynamic and does not require reloading the page. Changing the sort method is applied directly (except for the Category in multiselect mode in v1.3.7 :grin:).

**Closed by eneiluj** 2021-09-27 08:54 UTC
Labels: question
