### ISSUE TITLE
Duplicate members when importing a project from CSV

### ISSUE THREAD

**Issue by mrclschstr** [eneiluj/cospend-nc#97] opened 2021-10-28 19:37 UTC
I just noticed that there is a bug regarding the CSV import when you have members containing a blank. The import strips the whitespaces resulting in duplicate members and incorrect balances.

Example: You have a project with members "John Doe" and "Jane Doe". After importing this project from CSV you have the four members "John Doe", "Jane Doe", "JohnDoe" and "JaneDoe".

I had a quick look at the code and noticed the following line. This replaces all whitespaces from the `owners` CSV column, which is probably the reason for the error. https://github.com/eneiluj/cospend-nc/blob/d24998d591403f67ddf68ee3e833208dcf622885/lib/Service/ProjectService.php#L5401

**EDIT:**
- Nextcloud version: 22.2.0
- Cospend version: 1.4.1

**Comment by helloha82** [comment] 2022-03-10 21:40
Was this fixed? Because I'm having this issue...

**Comment by mrclschstr** [comment] 2022-03-10 22:36
Unfotunately not. My workaround was to edit the CSV with a texteditor like Notepad++ to have member namens without spaces and renaming them after import.

**Comment by eneiluj** [comment] 2022-03-11 07:59
Hey there. Thanks for the bug report. It's now fixed. New release is coming soon.

**Comment by eneiluj** [comment] 2022-07-20 14:02
@falzonv Thanks for reporting this. Are you sure there are spaces following comas for the owers field in csv files produced by Cospend? There shouldn't be any.

Anyway, the import process now trims each ower. This is available in latest nightly (v1.4.9-2-nightly). It would be nice if you could try it.

**Comment by falzonv** [comment] 2022-07-21 16:39
Hello,

You are right, actually the exports came from an older version of Cospend (yesterday I had to reinstall Nextcloud, looking at my DB backup it was Cospend 1.3.7 on Nextcloud 21). I noticed the bug when importing projects back in the new instance *(\*)*.
I just tested an export now with Cospend 1.4.8 on Nextcloud 24.0.3 and indeed the spaces are not there.

*(\*) By the way, in my exports I also had some members with spaces in their name and those ones were properly imported so I can confirm that the original bug of this ticket is solved.*

Regarding testing, I would prefer to let my Nextcloud instance on the stable channel.
Is there a way to update only Cospend to latest nightly?

Best regards.

**Comment by falzonv** [comment] 2022-07-21 16:41
> Regarding testing, I would prefer to let my Nextcloud instance on the stable channel.
Is there a way to update only Cospend to latest nightly?

Sorry, just found it at the bottom of the README...

**Comment by falzonv** [comment] 2022-07-21 17:14
I was able to test version 1.4.9-2 but unfortunately the fix doesn't seem to work properly:
- With an older export (containing spaces between members), the import process stops and an error is displayed at the first line of a cost containing spaces between members (spaces in the name of a member are ok)
- With a normal export (containing no spaces between members) everything works as expected

Here is an example file that I just created and where I added spaces likes in the older exports, if you want to test:
[test_2022-07-21.csv](https://github.com/eneiluj/cospend-nc/files/9161363/test_2022-07-21.csv)

**Comment by eneiluj** [comment] 2022-07-21 21:40
@falzonv Thanks for the precise feedback. Yeah right I didn't test my fix. It's now properly fixed and available in v1.4.9-3-nightly.

**Comment by falzonv** [comment] 2022-07-24 07:45
Hello @eneiluj,

Just checked with v1.4.9-3 and indeed the issue is solved, thank you very much!

Best regards.

**Comment by eneiluj** [comment] 2022-07-26 10:17
@falzonv Nice! Thanks for testing it.

Closing this, feel free to reopen if needed.

**Closed by eneiluj** 2022-07-26 10:17 UTC
Labels: bug, testing
