### ISSUE TITLE
Feature Request: Archive old projects

### ISSUE THREAD

**Issue by Skamandros** [eneiluj/cospend-nc#102] opened 2021-11-17 09:34 UTC
I'm using Cospend more and more, because it works great and makes it much easier to split the costs of events with my friends. :) However, this leads to many projects in the list. Most of them are already settled, so I don't really need them anymore. But for future reference, I don't want to delete them either. This is why an archive function would be great so that I could select to archive a project which then no longer shows in the main list, but can be found in some kind of "archived projects" list. It's a minor thing, but it would be cool.

**Comment by LeoColman** [comment] 2022-03-28 18:11
I tried to add more details to this issue using a new one, #128.

I'd like to suggest closing this one as a duplicate of #128, or adding #128 info here and closing it as a duplicate.

**Comment by Skamandros** [comment] 2022-05-05 08:48
Closed in favor of #128

**Closed** 2022-05-05 08:48 UTC
