### ISSUE TITLE
Unable to delete project even if I am the creator

### ISSUE THREAD

**Issue by GirardR1006** [eneiluj/cospend-nc#81] opened 2021-09-04 22:01 UTC
Hello, 

I am unable to delete a project I created with MoneyBuster Android. Either through cospend-nc or MoneyBuster, it says that I am unable to access the project.

cospend-nc:
![2021-09-04_23-58](https://user-images.githubusercontent.com/19275558/132108978-6579e41b-1d2b-49e1-9f85-2239a804e484.png)

MoneyBuster client:
![signal-2021-09-04-235935](https://user-images.githubusercontent.com/19275558/132109006-8e3abc9a-f4e0-45f1-bbeb-31904768d9e9.png)

Is there a way to delete this project through some kind of database manipulation?

**Comment by eneiluj** [comment] 2021-09-05 21:36
Hi, thanks for the bug report.

This issue is caused by a conception mistake :grin:. The default public access permissions are "participant". You can't delete a project with those permissions. As the project is not attached to any Nextcloud user, there is no project admin who can delete the project.

Easiest way to delete the project is to affect the project to a Nextcloud user and then delete the project in the user's project list in Cospend. Here is the SQL request:
``` sql
update oc_cospend_projects set userid='A_NEXTCLOUD_USER_ID' where projectid='THE_PROJECT_ID';
```

You can also delete the project directly in the database, but then you have to take care of all associated tables like members, bills etc... Easier to use the web UI like I suggested.

I'll figure a way to get rid of this kind of problems.
Feel free to ask for more information.

**Comment by GirardR1006** [comment] 2021-09-06 09:59
Thank for your quick answer, I will use your fix.

To clarify, I need to input the SQL request you gave, then proceed to delete the project via the web UI, correct?
I never directly manipulated databases before, so a couple more questions:
  * do you know where I can have the ids of both nextcloud user and ghost cospend project?
  * I have postgresql as a database for nextcloud. Should I log into the postgresql shell to perform this SQL command?

**Comment by eneiluj** [comment] 2021-09-06 10:07
> I need to input the SQL request you gave, then proceed to delete the project via the web UI, correct?

Yes.

> do you know where I can have the ids of both nextcloud user and ghost cospend project?

The Nextcloud user IDs are visible in the user settings (if you're logged in as an admin). They are displayed next to the display names. make sure not to use a display name :grin:. I mean it will do no harm but you won't see the project in any user's Cospend project list.

You can list your projects IDs with this SQL query:
``` sql
select id from oc_cospend_projects where 1;
```

> Should I log into the postgresql shell to perform this SQL command?

Yes, once you are in a postgresql shell which is set to query your Nextcloud's database, just paste the SQL queries I gave you.

**Comment by GirardR1006** [comment] 2021-09-06 12:48
After some digging (again, I'm a DB noob), I was able to reach my NC database, however there is an issue:
```
nextcloud=> update oc_cospend_projects set userid='userid' where projectid='R��daction au vert';
ERROR:  column "projectid" does not exist
```

**Comment by eneiluj** [comment] 2021-09-06 12:52
Ok sorry, partially my fault, you made a mistake too :grin:.

The request is
``` sql
update oc_cospend_projects set userid='A_NEXTCLOUD_USER_ID' where id='THE_PROJECT_ID';
```
I made a mistake on the column name.
But the project ID "R��daction au vert" is wrong. This is most likely the project's display name. Make sure you use what you find in the `id` column of the `select id from oc_cospend_projects where 1;` query. These are the project IDs.

Any better?

**Comment by GirardR1006** [comment] 2021-09-06 13:02
Indeed, but as far as I know I only get the project's display name (`where 1` syntax does not work on my db, pgsql 13.4):
```
nextcloud=> select id from oc_cospend_projects where true;
         id         
--------------------
 coloc-jujujuju
 Rédaction au vert 
(2 rows)
```

**Comment by eneiluj** [comment] 2021-09-06 13:09
Ok this might be an ID after all. Did you try the fixed SQL request?
``` sql
update oc_cospend_projects set userid='toto' where id='Rédaction au vert';
```
Replace toto with an existing Nextcloud user ID.

**Comment by GirardR1006** [comment] 2021-09-06 13:21
ah snap, forgot to change the `toto` -_-

```
nextcloud=> update oc_cospend_projects set userid='toto' where id='Rédaction au vert';
UPDATE 0
nextcloud'> update oc_cospend_projects set userid='arikado' where id='Rédaction au vert';
nextcloud'>
```
update was performed first time I inputted the update, not the second time D:

**Comment by eneiluj** [comment] 2021-09-06 13:25
According to your prompt, the request was not triggered the second time because pgsql considers it is not complete. Like if the ";" was missing at the end or something similar (unfinished string, that kind of stuff).

You see, the prompt was `nextcloud=>` and became `nextcloud'>`.

Just in case, try to close pqsql, open it again and run the query. It might do.

**Comment by GirardR1006** [comment] 2021-09-06 13:31
Okay, I successfully updated the query with the correct used ID, but I still have the original error on the Cospend UI, while being connected with my user (who happen to be the admin of the NC instance)

**Comment by eneiluj** [comment] 2021-09-06 14:05
Ok now I guess it's because of the accents. I guess MoneyBuster does not get rid of special characters in project ID when creating a project... And then the ID messes with your pgsql encoding.

Let's take a shorter path: You can delete the project with those SQL requests:
``` sql
delete from oc_cospend_bills where projectid='Rédaction au vert';
delete from oc_cospend_members where projectid='Rédaction au vert';
delete from oc_cospend_project_categories where projectid='Rédaction au vert';
delete from oc_cospend_projects where id='Rédaction au vert';
```

**Comment by GirardR1006** [comment] 2021-09-06 14:11
Just did that and got DELETE 0, project is still in the UI even after restarting the Database.

**Comment by eneiluj** [comment] 2021-09-06 14:18
Thanks for your patience. Ok let's try that:
``` sql
delete from oc_cospend_projects where id like '%au vert';
```
If it actually deletes the entry in the `oc_cospend_projects` table, then run those queries too:
``` sql
delete from oc_cospend_bills where projectid like '%au vert';
delete from oc_cospend_members where projectid like '%au vert';
delete from oc_cospend_project_categories where projectid like '%au vert';
```

**Comment by GirardR1006** [comment] 2021-09-06 14:45
> Thanks for your patience. Ok let's try that:

Thank you to you for guiding me !

```
nextcloud=> delete from oc_cospend_projects where id like '%au vert';
DELETE 0
```
not working as far as I can see :(

**Comment by eneiluj** [comment] 2021-09-06 14:58
Could you show me again the result of
``` sql
select id from oc_cospend_projects where true;
```
?

And maybe try this one (if you don't have any other project with "vert" in the ID:
``` sql
delete from oc_cospend_projects where id like '%vert%';
```

**Comment by GirardR1006** [comment] 2021-09-06 15:01
Last one worked, the project disappeared from Cospend UI and MoneyBuster :D 

Do you want me to close this issue, or to keep it open for further reference?

**Comment by eneiluj** [comment] 2021-09-06 15:03
Let's close it.

If you want to make sure all related data is deleted in the DB you should also run:
``` sql
delete from oc_cospend_bills where projectid like '%vert%';
delete from oc_cospend_members where projectid like '%vert%';
delete from oc_cospend_project_categories where projectid like '%vert%';
```

**Closed by eneiluj** 2021-09-06 15:03 UTC
Labels: bug, todo
